name: Run clang-format-lint
# https://github.com/marketplace/actions/clang-format-lint

# Trigger the workflow on pull request (assigned) event for the branch
# https://help.github.com/en/actions/reference/events-that-trigger-workflows
# change

on:
  pull_request:
    branches: [dev]
    types:    [assigned]

jobs:

  clang_format_linter:
      timeout-minutes: 30
      runs-on: ubuntu-latest
      if: ${{ github.event.assignee.login == 'smithw-adsk' }}
      steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.11
        with:
          source: '.'
          clangFormatVersion: 10